# title del head
title: "eFrolic"
subtitle: "CSS framework which without using JavaScript is interactive and animated."

# description
description: "It is a CSS framework, which without using javascript is interactive and animated.
This CSS framework is based on being simple and modern in mobile first web development. Built on Flexbox bases,
focused on responsive design."

# Social
photo_profile: "/assets/images/post/profile/profile-3.jpeg"
twitter: "https://twitter.com/e_frolic"
github: "https://github.com/EfraaX/eFrolic"
github_me: "https://github.com/EfraaX"
facebook: "https://www.facebook.com/Efrolicss-954443128098679/"
donate: "https://www.paypal.me/efraperalta"


# CSS
css_cdn: "https://unpkg.com/efrolic@0.2.9/dist/css/efrolic.min.css"
css_github: "http://efrolicss.com/assets/css/dist/efrolic.min.css"
fontawesome: "https://use.fontawesome.com/releases/v5.3.1/css/all.css"
fontawesome_integrity: "sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU"
files_css: "/assets/download/eFrolic.zip"
files_sass: "/assets/download/eFrolic-Sass.zip"

# Config
button: anime primary
button_secondary: anime inverted primary
button_optional: anime inverted danger
button_header: anime inverted danger
text_color: rgba(0, 0, 0, .5)
bg_color: white
title_color: 1da1f2

# Page default
lang: en
ref: hello

# Build settings
version: "V0.2.9"
markdown: kramdown
url: "https://efrolicss.com"
permalink: pretty
exclude: ['node_modules', 'gulpfile.js', 'package-lock.json', 'Gemfile', 'Gemfile.lock', 'feed.xml']
